In [1]:
#Importing libraries
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.optim as optim
import torch.utils.data
from torch.autograd import Variable

In [2]:
#Importing dataset
movies = pd.read_csv('./Movie review dataset/ml-1m/movies.dat', sep='::', header=None,engine='python',encoding='latin-1')
users = pd.read_csv('./Movie review dataset/ml-1m/users.dat', sep='::', header=None,engine='python',encoding='latin-1')
ratings = pd.read_csv('./Movie review dataset/ml-1m/ratings.dat',sep='::',header=None,engine='python',encoding='latin-1')

In [3]:
movies.head()

   0                                   1                             2
0  1                    Toy Story (1995)   Animation|Children's|Comedy
1  2                      Jumanji (1995)  Adventure|Children's|Fantasy
2  3             Grumpier Old Men (1995)                Comedy|Romance
3  4            Waiting to Exhale (1995)                  Comedy|Drama
4  5  Father of the Bride Part II (1995)                        Comedy

In [4]:
users.head()

   0  1   2   3      4
0  1  F   1  10  48067
1  2  M  56  16  70072
2  3  M  25  15  55117
3  4  M  45   7  02460
4  5  M  25  20  55455

In [5]:
ratings.head()

   0     1  2          3
0  1  1193  5  978300760
1  1   661  3  978302109
2  1   914  3  978301968
3  1  3408  4  978300275
4  1  2355  5  978824291

In [6]:
#Preparing the training set and the test traset
training_set = pd.read_csv('./Movie review dataset/ml-100k/u1.base', delimiter='\t')
training_set = np.array(training_set, dtype='int')
test_set = pd.read_csv('./Movie review dataset/ml-100k/u1.test',delimiter='\t')
test_set = np.array(test_set,dtype='int')

In [7]:
training_set.shape

(79999, 4)

In [8]:
test_set.shape

(19999, 4)

In [9]:
#getting no. of users and movies
nb_user = int(max(max(training_set[:,0]) , max(test_set[:,0])))
nb_movies = int(max(max(training_set[:,1]) , max(test_set[:,1])))

In [10]:
#Converting the data into an array with users in lines and movies in columns
def convert(data):
    new_data = []
    for id_user in range(1,nb_user + 1):
        id_movies = data[:,1][data[:,0] == id_user]
        id_ratings = data[:,2][data[:,0] == id_user]
        ratings = np.zeros(nb_movies)
        ratings[id_movies - 1] = id_ratings
        new_data.append(list(ratings))
    
    return new_data

In [11]:
training_set = convert(training_set)
test_set = convert(test_set)

In [12]:
#Converting the data into torch tensors
training_set = torch.FloatTensor(training_set)
test_set = torch.FloatTensor(test_set)

In [13]:
class SAE(nn.Module):
    def __init__(self,):
        super(SAE,self).__init__()
        self.fc1 = nn.Linear(nb_movies,20)
        self.fc2 = nn.Linear(20,10)
        self.fc3 = nn.Linear(10,20)
        self.fc4 = nn.Linear(20,nb_movies)
        self.activation = nn.Sigmoid()
    
    def forward(self,x):
        x = self.activation(self.fc1(x))
        x = self.activation(self.fc2(x))
        x = self.activation(self.fc3(x))
        x = self.fc4(x)
        return x

In [14]:
sae = SAE()
criterion = nn.MSELoss()
optimiser = optim.RMSprop(sae.parameters(),lr=0.01,weight_decay=0.5)

In [15]:
#Training SAE
nb_epochs=200
for epoch in range(nb_epochs):
    train_loss=0
    s=0
    for id_user in range(nb_user):
        input = Variable(training_set[id_user]).unsqueeze(0)
        target = input.clone()
        if torch.sum(target.data > 0) > 0:
            output = sae(input)
            target.require_grad = False
            output[target == 0] = 0
            loss = criterion(output,target)
            mean_corrector = nb_movies/float(torch.sum(target.data > 0) + 1e-10)
            loss.backward()
            train_loss += np.sqrt(loss.data[0] * mean_corrector)
            s+=1
            optimiser.step()
    print('epoch: ' + str(epoch) + ' loss: ' + str(train_loss/s))

/home/sumit/DL/lib/python3.5/site-packages/ipykernel_launcher.py:16: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  app.launch_new_instance()

epoch: 0 loss: tensor(1.7716)
epoch: 1 loss: tensor(1.0966)
epoch: 2 loss: tensor(1.0534)
epoch: 3 loss: tensor(1.0384)
epoch: 4 loss: tensor(1.0309)
epoch: 5 loss: tensor(1.0268)
epoch: 6 loss: tensor(1.0240)
epoch: 7 loss: tensor(1.0218)
epoch: 8 loss: tensor(1.0206)
epoch: 9 loss: tensor(1.0198)
epoch: 10 loss: tensor(1.0185)
epoch: 11 loss: tensor(1.0184)
epoch: 12 loss: tensor(1.0177)
epoch: 13 loss: tensor(1.0176)
epoch: 14 loss: tensor(1.0174)
epoch: 15 loss: tensor(1.0166)
epoch: 16 loss: tensor(1.0167)
epoch: 17 loss: tensor(1.0166)
epoch: 18 loss: tensor(1.0165)
epoch: 19 loss: tensor(1.0161)
epoch: 20 loss: tensor(1.0161)
epoch: 21 loss: tensor(1.0160)
epoch: 22 loss: tensor(1.0157)
epoch: 23 loss: tensor(1.0159)
epoch: 24 loss: tensor(1.0156)
epoch: 25 loss: tensor(1.0155)
epoch: 26 loss: tensor(1.0152)
epoch: 27 loss: tensor(1.0147)
epoch: 28 loss: tensor(1.0130)
epoch: 29 loss: tensor(1.0120)
epoch: 30 loss: tensor(1.0092)
epoch: 31 loss: tensor(1.0095)
epoch: 32 loss: tensor(1.0056)
epoch: 33 loss: tensor(1.0042)
epoch: 34 loss: tensor(1.0008)
epoch: 35 loss: tensor(0.9995)
epoch: 36 loss: tensor(0.9963)
epoch: 37 loss: tensor(0.9951)
epoch: 38 loss: tensor(0.9920)
epoch: 39 loss: tensor(0.9912)
epoch: 40 loss: tensor(0.9896)
epoch: 41 loss: tensor(0.9889)
epoch: 42 loss: tensor(0.9849)
epoch: 43 loss: tensor(0.9885)
epoch: 44 loss: tensor(0.9850)
epoch: 45 loss: tensor(0.9886)
epoch: 46 loss: tensor(0.9797)
epoch: 47 loss: tensor(0.9775)
epoch: 48 loss: tensor(0.9749)
epoch: 49 loss: tensor(0.9744)
epoch: 50 loss: tensor(0.9708)
epoch: 51 loss: tensor(0.9727)
epoch: 52 loss: tensor(0.9672)
epoch: 53 loss: tensor(0.9773)
epoch: 54 loss: tensor(0.9749)
epoch: 55 loss: tensor(0.9741)
epoch: 56 loss: tensor(0.9746)
epoch: 57 loss: tensor(0.9808)
epoch: 58 loss: tensor(0.9780)
epoch: 59 loss: tensor(0.9725)
epoch: 60 loss: tensor(0.9758)
epoch: 61 loss: tensor(0.9754)
epoch: 62 loss: tensor(0.9724)
epoch: 63 loss: tensor(0.9741)
epoch: 64 loss: tensor(0.9766)
epoch: 65 loss: tensor(0.9735)
epoch: 66 loss: tensor(0.9701)
epoch: 67 loss: tensor(0.9759)
epoch: 68 loss: tensor(0.9772)
epoch: 69 loss: tensor(0.9769)
epoch: 70 loss: tensor(0.9736)
epoch: 71 loss: tensor(0.9722)
epoch: 72 loss: tensor(0.9705)
epoch: 73 loss: tensor(0.9785)
epoch: 74 loss: tensor(0.9760)
epoch: 75 loss: tensor(0.9706)
epoch: 76 loss: tensor(0.9743)
epoch: 77 loss: tensor(0.9737)
epoch: 78 loss: tensor(0.9706)
epoch: 79 loss: tensor(0.9671)
epoch: 80 loss: tensor(0.9662)
epoch: 81 loss: tensor(0.9656)
epoch: 82 loss: tensor(0.9622)
epoch: 83 loss: tensor(0.9615)
epoch: 84 loss: tensor(0.9591)
epoch: 85 loss: tensor(0.9596)
epoch: 86 loss: tensor(0.9588)
epoch: 87 loss: tensor(0.9591)
epoch: 88 loss: tensor(0.9639)
epoch: 89 loss: tensor(0.9568)
epoch: 90 loss: tensor(0.9538)
epoch: 91 loss: tensor(0.9534)
epoch: 92 loss: tensor(0.9509)
epoch: 93 loss: tensor(0.9525)
epoch: 94 loss: tensor(0.9509)
epoch: 95 loss: tensor(0.9508)
epoch: 96 loss: tensor(0.9484)
epoch: 97 loss: tensor(0.9502)
epoch: 98 loss: tensor(0.9480)
epoch: 99 loss: tensor(0.9483)
epoch: 100 loss: tensor(0.9463)
epoch: 101 loss: tensor(0.9474)
epoch: 102 loss: tensor(0.9443)
epoch: 103 loss: tensor(0.9452)
epoch: 104 loss: tensor(0.9420)
epoch: 105 loss: tensor(0.9437)
epoch: 106 loss: tensor(0.9411)
epoch: 107 loss: tensor(0.9415)
epoch: 108 loss: tensor(0.9407)
epoch: 109 loss: tensor(0.9417)
epoch: 110 loss: tensor(0.9403)
epoch: 111 loss: tensor(0.9409)
epoch: 112 loss: tensor(0.9386)
epoch: 113 loss: tensor(0.9394)
epoch: 114 loss: tensor(0.9372)
epoch: 115 loss: tensor(0.9398)
epoch: 116 loss: tensor(0.9376)
epoch: 117 loss: tensor(0.9391)
epoch: 118 loss: tensor(0.9365)
epoch: 119 loss: tensor(0.9375)
epoch: 120 loss: tensor(0.9357)
epoch: 121 loss: tensor(0.9361)
epoch: 122 loss: tensor(0.9348)
epoch: 123 loss: tensor(0.9355)
epoch: 124 loss: tensor(0.9344)
epoch: 125 loss: tensor(0.9348)
epoch: 126 loss: tensor(0.9335)
epoch: 127 loss: tensor(0.9340)
epoch: 128 loss: tensor(0.9332)
epoch: 129 loss: tensor(0.9337)
epoch: 130 loss: tensor(0.9325)
epoch: 131 loss: tensor(0.9328)
epoch: 132 loss: tensor(0.9324)
epoch: 133 loss: tensor(0.9321)
epoch: 134 loss: tensor(0.9313)
epoch: 135 loss: tensor(0.9322)
epoch: 136 loss: tensor(0.9309)
epoch: 137 loss: tensor(0.9318)
epoch: 138 loss: tensor(0.9305)
epoch: 139 loss: tensor(0.9314)
epoch: 140 loss: tensor(0.9294)
epoch: 141 loss: tensor(0.9350)
epoch: 142 loss: tensor(0.9340)
epoch: 143 loss: tensor(0.9341)
epoch: 144 loss: tensor(0.9324)
epoch: 145 loss: tensor(0.9326)
epoch: 146 loss: tensor(0.9306)
epoch: 147 loss: tensor(0.9324)
epoch: 148 loss: tensor(0.9306)
epoch: 149 loss: tensor(0.9321)
epoch: 150 loss: tensor(0.9303)
epoch: 151 loss: tensor(0.9308)
epoch: 152 loss: tensor(0.9293)
epoch: 153 loss: tensor(0.9305)
epoch: 154 loss: tensor(0.9285)
epoch: 155 loss: tensor(0.9300)
epoch: 156 loss: tensor(0.9288)
epoch: 157 loss: tensor(0.9301)
epoch: 158 loss: tensor(0.9281)
epoch: 159 loss: tensor(0.9292)
epoch: 160 loss: tensor(0.9283)
epoch: 161 loss: tensor(0.9285)
epoch: 162 loss: tensor(0.9269)
epoch: 163 loss: tensor(0.9277)
epoch: 164 loss: tensor(0.9278)
epoch: 165 loss: tensor(0.9286)
epoch: 166 loss: tensor(0.9261)
epoch: 167 loss: tensor(0.9269)
epoch: 168 loss: tensor(0.9256)
epoch: 169 loss: tensor(0.9263)
epoch: 170 loss: tensor(0.9246)
epoch: 171 loss: tensor(0.9258)
epoch: 172 loss: tensor(0.9251)
epoch: 173 loss: tensor(0.9257)
epoch: 174 loss: tensor(0.9245)
epoch: 175 loss: tensor(0.9248)
epoch: 176 loss: tensor(0.9233)
epoch: 177 loss: tensor(0.9244)
epoch: 178 loss: tensor(0.9234)
epoch: 179 loss: tensor(0.9239)
epoch: 180 loss: tensor(0.9233)
epoch: 181 loss: tensor(0.9234)
epoch: 182 loss: tensor(0.9236)
epoch: 183 loss: tensor(0.9234)
epoch: 184 loss: tensor(0.9228)
epoch: 185 loss: tensor(0.9229)
epoch: 186 loss: tensor(0.9228)
epoch: 187 loss: tensor(0.9228)
epoch: 188 loss: tensor(0.9220)
epoch: 189 loss: tensor(0.9225)
epoch: 190 loss: tensor(0.9219)
epoch: 191 loss: tensor(0.9220)
epoch: 192 loss: tensor(0.9215)
epoch: 193 loss: tensor(0.9215)
epoch: 194 loss: tensor(0.9209)
epoch: 195 loss: tensor(0.9212)
epoch: 196 loss: tensor(0.9207)
epoch: 197 loss: tensor(0.9217)
epoch: 198 loss: tensor(0.9203)
epoch: 199 loss: tensor(0.9203)

In [18]:
#Testing SAE
test_loss = 0
s = 0.
for id_user in range(nb_user):
    input = Variable(training_set[id_user]).unsqueeze(0)
    target = Variable(test_set[id_user])
    if torch.sum(target.data > 0) > 0:
        output = sae(input)
        target.require_grad = False
        output[target == 0] = 0
        loss = criterion(output, target)
        mean_corrector = nb_movies/float(torch.sum(target.data > 0) + 1e-10)
        test_loss += np.sqrt(loss.data[0]*mean_corrector)
        s += 1.
print('test loss: '+str(test_loss/s))

RuntimeError: The shape of the mask [1682] at index 0 does not match the shape of the indexed tensor [1, 1682] at index 0